### ISSUE TITLE
Improve documentation and code structure

### ISSUE THREAD

**Issue by mnsmar** [maragkakislab/nanoplen#25]
In README.md:
- [x] Step by step instructions for how to use the helper python tools.
- [x] Test datasets with step by step processing commands to use nanoplen.
- [x] Expand description of the output file.
- [x] Polish the text.

For code:
- [x] #22
- [x] #23
- [x] Remove travis.
- [x] Remove sam_per_ref_count_statistics.py cause it's not part of the nanoplen pipeline.
- [x] Prepare yaml file for suggested conda environment.
- [x] Add a descriptive header in the R script.
- [x] Add helper python scripts that can create simple plots following `diff_length.R` execution. Add example images in `README.md` for the example data.
- [x] Delete existing code in `tests/` and replace with unit tests for the R code.

**Comment by leetaiyi** [comment]
sam_per_ref_count_statistics.py removed

**Comment by leetaiyi** [comment]
.

**Comment by leetaiyi** [comment]
Unit test framework and many unit tests made. Can add additional at any time.

**Comment by leetaiyi** [comment]
R scripts documented but needs proofreading

**Comment by leetaiyi** [comment]
Left "Polish the text" unchecked until more proofreading done
