### ISSUE TITLE
no transcript name using cDNA nanopore sequencing

### ISSUE THREAD

**Issue by Xingliang888** [maragkakislab/nanoplen#35]
Hi,
I am trying using bam files from nanopore sequencing to analyze the poly(A) length, in the first step, I am trying to run:
python /nanoplen/scripts/bam_to_readlength.py --ifile 1.aln.sorted.bam --ref-col-name transcript --len-col-name read_length --opt-col-name sample --opt-col-val WT_1 --no-zeros > WT_1_transcripts_list.tab
However, the results show like this: 
sample	transcript	read_length
WT_1	1	2900
WT_1	1	0
WT_1	1	264
WT_1	1	240
WT_1	1	0
WT_1	1	298
WT_1	1	264
WT_1	1	0
WT_1	1	276
It seems no transcript ID included. Anyone know what's wrong here?
BY THE WAY, the example bam files work well.

Thank you.

**Comment by mnsmar** [comment]
Hi @Xingliang888 , 

Is `1.aln.sorted.bam` a genome alignment or a transcriptome alignment? The helper script `bam_to_readlength.py` assumes alignments on the reference transcriptome.

Manolis

**Comment by dar19** [comment]
Hi @Xingliang888

The script "_bam_to_readlength.py_" uses 'transcriptome aligned bam file' for transcript length calculations for each transcript and NOT for polyA-tail lengths.

However, For polyA tail lengths, there is no preprocessed step in NanopLen. You will require the primary file of transcript(s) with respective polyA lengths to be calculated e.g. using **nanopolish polyA module** (https://nanopolish.readthedocs.io/en/latest/quickstart_polya.html). Then you can process, modify and provide the polyA-file (from nanopolish polya) from next step (awk ...) in the pipeline [with file format as that of _bam_to_readlength.py_].

Hope that answers your question.
Thank you.

**Comment by Mingzhuge** [comment]
> Hi @Xingliang888 ,
> 
> Is `1.aln.sorted.bam` a genome alignment or a transcriptome alignment? The helper script `bam_to_readlength.py` assumes alignments on the reference transcriptome.
> 
> Manolis

Hi, Manolis,
Thank you for your reminder, I think I mistook it, the files are mapped to genome. I will map to transcriptome and try again.
Xingliang

**Comment by Xingliang888** [comment]
> Hi @Xingliang888
> 
> The script "_bam_to_readlength.py_" uses 'transcriptome aligned bam file' for length calculations of each transcript and NOT for polyA-tail lengths.
> 
> However, for polyA tail lengths, there is no preprocessed step in NanopLen. You will require the primary file of transcript(s) with respective polyA lengths to be calculated e.g. using **nanopolish polyA module** (https://nanopolish.readthedocs.io/en/latest/quickstart_polya.html). Then you can process, modify and provide the polyA-file (from nanopolish polya) from next step (awk ...) in the pipeline [with file format as that of _bam_to_readlength.py_].
> 
> Also, please check the SAM/BAM file and compare with the example BAM file.
> 
> Hope that answers your question. Thank you.

Hi, dar19,
I got your point. So, does it means if we got the poly(A) length by nanopolish polyA, we can using the poly(A) length replacing the transcript length, then do the following difference analysis?
Thank you.

**Comment by dar19** [comment]
> > Hi @Xingliang888
> > The script "_bam_to_readlength.py_" uses 'transcriptome aligned bam file' for length calculations of each transcript and NOT for polyA-tail lengths.
> > However, for polyA tail lengths, there is no preprocessed step in NanopLen. You will require the primary file of transcript(s) with respective polyA lengths to be calculated e.g. using **nanopolish polyA module** (https://nanopolish.readthedocs.io/en/latest/quickstart_polya.html). Then you can process, modify and provide the polyA-file (from nanopolish polya) from next step (awk ...) in the pipeline [with file format as that of _bam_to_readlength.py_].
> > Also, please check the SAM/BAM file and compare with the example BAM file.
> > Hope that answers your question. Thank you.
> 
> Hi, dar19, I got your point. So, does it means if we got the poly(A) length by nanopolish polyA, we can using the poly(A) length replacing the transcript length, then do the following difference analysis? Thank you.

Yes absolutely.

**Comment by mnsmar** [comment]
@Xingliang888  I'm closing this. Feel free to reopen if the issue persists.
