### ISSUE TITLE
SyntaxError: invalid syntax in diff_length.R

### ISSUE THREAD

**Issue by Xingliang888** [maragkakislab/nanoplen#36]
Hi, 
when I test diff_length script using mouse transcript length (this is similar to example file but the transcript name length), it comes out with error:

File "./scripts/diff_length.R", line 31
    vars = sapply(1:(length(option_list)), function(i) {substr(option_list[[i]]@long_flag,3,1000)})
                   ^
SyntaxError: invalid syntax
![image](https://github.com/maragkakislab/nanoplen/assets/157734790/b42a7f2a-a884-4506-8a75-1353882454af)
![image](https://github.com/maragkakislab/nanoplen/assets/157734790/fa7f082f-985b-421b-93ac-f28d927004dc)

**Comment by leetaiyi** [comment]
That's... odd. Out of all the errors, I can't see why it would give you a syntax error

**Comment by leetaiyi** [comment]
@Xingliang888 Is it still happening?

**Comment by Xingliang888** [comment]
Hi, 
Yes, it still exist. I use biowulf, the R is the default loaded version, see the picture.
![image](https://github.com/maragkakislab/nanoplen/assets/157734790/f7310a59-b7a4-4b98-80c4-274848485ea5)

The session info is also indicated in the picture. the python version is 3.9.15.
![image](https://github.com/maragkakislab/nanoplen/assets/157734790/7a5805f9-7c6a-48a5-8a1c-ec9a01cb3f87)

**Comment by leetaiyi** [comment]
Hmm yeah sorry, I really cannot imagine why you'd get a syntax error. The only possibility I can think of is if you copy-pasted the code in another language that uses different symbol types. Like my Chinese parentheses are different from English parentheses

**Comment by Xingliang888** [comment]
No, maybe not. The executing script has changed to unix using dos2unix. It’s fine, forget about that.

Thank you.

Xingliang
