### ISSUE TITLE
Error in running diff_length.R

### ISSUE THREAD

**Issue by doshirLV** [maragkakislab/nanoplen#37]
Hello Maragkakis Lab,

`Error in names(x) <- value :`
`  'names' attribute [2] must be the same length as the vector [1]`
`Calls: nanoplen -> colnames<-`
`Execution halted`

Conda environment installed successfully and active. Nanoplen R package runs properly with test data. My data is in the same format. But the samples in the metadata file are in a different order than they appear in the input file. 

R version 4.2.2 (2022-10-31) running on Ubuntu 20.04.5 LTS

Thank you in advance for your help,
Raj

**Comment by leetaiyi** [comment]
Hi Raj,

Can you send me a `head` of what your data looks like?

Chris

**Comment by doshirLV** [comment]
I appreciate your swift response Chris,

**Input file:**
```
sample  trxID   polyA_len
1    ENST00000000233.10      33.0
1    ENST00000000233.10      33.0
1    ENST00000000233.10      41.0
1    ENST00000000233.10      42.0
```

**Metadata file:**
```
sample  condition
10   treatment
7    treatment
1    treatment
16   treatment
```

Feel free to let me know if you need anything else

**Comment by leetaiyi** [comment]
Hmm, I may need your full files to discover what's wrong. I'm trying to resolve this same issue with someone else's data as well

**Comment by doshirLV** [comment]
> Hmm, I may need your full files to discover what's wrong. I'm trying to resolve this same issue with someone else's data as well
> 
> Edit: The other issue is not the same as yours

Hello Chris,

Any update on what the issue may be? Unfortunately I am unable to send the full files as it is patient data. But I could provide you metrics such as the size of the file or the order of the samples. 

Thank you for your diligence,
Raj

**Comment by leetaiyi** [comment]
It looks as simple as a delimiter issue but from what you showed me, it doesn't seem like that's the case.

**Comment by leetaiyi** [comment]
At this point I am reasonably sure it is something with your input data or your command. I've successfully just run a bunch of other data without issues

**Comment by doshirLV** [comment]
I appreciate you double checking Chris,

Could it be that my sample order is different in the input and metadata files?
So in the input file sample order is 1, 10, 11 .. 19, 2, 3 .. 9. 
Versus the metadata file is random:
10   treatment
7    treatment
1    treatment
16   treatment
6    treatment
11   control
17   control
12   control
5    treatment
19   control
8    treatment
3    control
14   control
18   treatment
4    control
13   control
15   treatment
2    control

**Comment by leetaiyi** [comment]
No, my metadata is also pretty scrambled, and it merges with the data via your library ID anyway

**Comment by doshirLV** [comment]
So weird, I am using the exact same command and it works for the "format" test data but gives error for mine.

**Test:**
```
./scripts/R/nanoplen/scripts/diff_length.R \
-d ./scripts/R/nanoplen/examples/nanoplen_input_format.tab \
-m ./scripts/R/nanoplen/examples/metadata_format.tab \
-b "control" \
-t m \
-o ./scripts/R/nanoplen/examples/nanoplen_output_format_LinearMixedModel_2024Oct08.tab
```

**Error:**
```
./scripts/R/nanoplen/scripts/diff_length.R \
-d ./projects/path/to/data/analysis/nanoplen/input.tab \
-m ./projects/path/to/data/analysis/nanoplen/metaData.tab \
-b "control" \
-t m \
-o ./projects/path/to/data/analysis/nanoplen/out_LMM_2024Oct08.tab
```
I will check for extra whitespace and how the tabs are formatted to confirm that it is not an issue with a delimiter. Also, file size should not be a problem, correct? I have 17+ million lines in the input file.
The only other thing I can think of is to go through your R scripts and see exactly where the error is occurring and change the corresponding code.

**Comment by leetaiyi** [comment]
No, size shouldn't be an issue code-wise. Were you able to try debugging line by line yourself?

**Comment by mnsmar** [comment]
Hi @doshirLV, has this issue been resolved?

**Comment by mnsmar** [comment]
I will close this due to inactivity. @doshirLV please feel free to reopen if the issue persists.

**Comment by renyi2517** [comment]
I met the same problem
After re-install nanoplen in other conda env , this issue been resolved
